/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controladores.productoControlador;
import controladores.proveedorControlador;
import java.math.BigDecimal;
import java.util.List;
import modelos.TblProducto;
import modelos.TblProveedor;

/**
 *
 * @author ERICK
 */
public class frmEditarProducto extends javax.swing.JFrame {

    /**
     * Creates new form frmEditarProducto
     */
    public int idProducto;
    public TblProveedor proveedorActual;
    public frmEditarProducto() {
        initComponents();
    }
    /*public frmEditarProducto(int id){
        initComponents();
        this.idProducto = id;
        cargarDatosProductos(id);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEditName = new javax.swing.JTextField();
        txtEditPrecio = new javax.swing.JTextField();
        nombreProveedor = new javax.swing.JLabel();
        cmbEditProveedor = new javax.swing.JComboBox<>();
        btnEditProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreProveedor.setText("jLabel1");

        cmbEditProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditProveedorActionPerformed(evt);
            }
        });

        btnEditProducto.setText("EDITAR");
        btnEditProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEditProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEditName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEditPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtEditName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEditPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEditProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnEditProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductoActionPerformed
        // TODO add your handling code here:
        productoControlador editar = new productoControlador();
        TblProducto productoEditar = new TblProducto();
        productoEditar.setIdproducto(idProducto);
        productoEditar.setNombreproducto(txtEditName.getText());
        productoEditar.setPrecio(BigDecimal.valueOf(Double.parseDouble(txtEditPrecio.getText())));
        
        TblProveedor prov = (TblProveedor)cmbEditProveedor.getSelectedItem();
        productoEditar.setIdproveedor(prov);
        editar.editarProducto(productoEditar);
    }//GEN-LAST:event_btnEditProductoActionPerformed

    private void cmbEditProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditProveedorActionPerformed
        // TODO add your handling code here:
        proveedorActual = (TblProveedor)cmbEditProveedor.getSelectedItem();
    }//GEN-LAST:event_cmbEditProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditarProducto().setVisible(true);
            }
        });
    }
    public void cargarProducto(){
        proveedorControlador cargar = new proveedorControlador();
        List<TblProveedor> listaProductos = cargar.getListProveedor();
        for(TblProveedor itemProveedor: listaProductos){
            cmbEditProveedor.addItem(itemProveedor.getNombreproveedor());
        }
    }
    public void cargarDatosProductos(int id){
        productoControlador cargar = new productoControlador();
        TblProducto pro = cargar.getProducto(id);
        txtEditName.setText(pro.getNombreproducto());
        txtEditPrecio.setText(pro.getPrecio().toString());
        TblProveedor prov = pro.getIdproveedor();
        nombreProveedor.setText("PROVEEDORES");
        cmbEditProveedor.addItem(prov.getNombreproveedor());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditProducto;
    private javax.swing.JComboBox<String> cmbEditProveedor;
    private javax.swing.JLabel nombreProveedor;
    private javax.swing.JTextField txtEditName;
    private javax.swing.JTextField txtEditPrecio;
    // End of variables declaration//GEN-END:variables
}
